services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wallet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - wallet-db:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/wallet
    ports:
      - "8000:8000"
    entrypoint: ["./entrypoint.sh"]
    command: ["app"]

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      app:
        condition: service_started
    environment:
      APP_BASE_URL: "http://app:8000"
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/test_wallet
    entrypoint: ["./entrypoint.sh"]
    command: ["test"]

volumes:
  wallet-db: